# Generated by Django 3.1.3 on 2020-11-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida_productos',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad en stock'),
        ),
    ]
