# Generated by Django 3.1.3 on 2020-12-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20201127_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidas',
            name='descripcion',
            field=models.CharField(max_length=700, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='partidas',
            name='nombre_partida',
            field=models.CharField(max_length=20, verbose_name='nombre_partida'),
        ),
        migrations.AlterField(
            model_name='partidas',
            name='numero_partida',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='numero_partida'),
        ),
    ]
