# Generated by Django 3.1.3 on 2020-12-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20201201_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidas',
            name='descripcion',
            field=models.CharField(max_length=700, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='partidas',
            name='nombre_partida',
            field=models.CharField(max_length=20, verbose_name='Nombre de partida'),
        ),
        migrations.AlterField(
            model_name='partidas',
            name='numero_partida',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Numero de partida'),
        ),
    ]
