# Generated by Django 3.1.3 on 2020-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20201201_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidas',
            name='numero_partida',
            field=models.IntegerField(max_length=4, primary_key=True, serialize=False, verbose_name='Numero de partida'),
        ),
    ]
