# Generated by Django 3.1.3 on 2020-11-27 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=150, verbose_name='Nombre del areas')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del empleado')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('appellido_materno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.area', verbose_name='Area de trabajo')),
            ],
        ),
    ]
